# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Global
  config.vm.box = "centos/7"

  # Global ssh key config

  config.ssh.insert_key = false
  config.ssh.private_key_path = ["/root/.ssh/id_rsa", "~/.vagrant.d/insecure_private_key"]

  # vagrant user
  config.vm.provision "file", source: "/root/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
  config.vm.provision "file", source: "/root/.ssh/id_rsa.pub", destination: "~/.ssh/id_rsa.pub"
  config.vm.provision "file", source: "/root/.ssh/id_rsa", destination: "/home/vagrant/.ssh/id_rsa"

  # ssh use key
  config.vm.provision "shell", inline: <<-EOC
    sudo sed -i -e "\\#PasswordAuthentication yes# s#PasswordAuthentication yes#PasswordAuthentication no#g" /etc/ssh/sshd_config
    sudo systemctl restart sshd
  EOC

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "init.yml"
  end

  # nodes
  (1..5).each do |i|
    config.vm.define "lab#{i}" do |node|
      node.vm.synced_folder ".", "/vagrant", type: "nfs"
      node.vm.hostname = "ctrl-#{i}"
      node.vm.provider :libvirt do |domain|
        domain.memory = 1024*2
        domain.volume_cache = "unsafe"
      end
    end
  end

end
