- hosts: localhost
  connection: local
  gather_facts: no
  become: true
  tasks:
    - name: Install packages
      yum:
        name:
          - ipmitool
          - libvirt
          - libvirt-devel
          - ruby-devel
          - gcc
          - qemu-kvm
          - make
          - automake
          - gcc
          - gcc-c++
          - kernel-devel
          - python-devel
          - libvirt-devel

    - name: Set ip forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: yes

    - name: Start libvirtd
      systemd:
        service: libvirtd
        state: started

    - name: Install python library
      pip:
        name:
          - ansible>=2.8
          - lxml
          - selinux
          - libvirt-python==5.0.0
          - virtualbmc==1.4.0
          - virtualenv

    - name: Generate openssh keypair
      openssh_keypair:
        path: /root/.ssh/id_rsa

    - name: Insert vagrant provider config to bashrc
      blockinfile:
        path: /root/.bashrc
        block: |
          export VAGRANT_DEFAULT_PROVIDER=libvirt

    - name: Install vagrant v2.2.7
      yum:
        name: 'https://releases.hashicorp.com/vagrant/2.2.7/vagrant_2.2.7_x86_64.rpm'

    - name: Create ssh proxy service
      copy:
        src: files/proxy.service
        dest: /usr/lib/systemd/system/proxyvm.service
      register: copy_service

    - name: Start proxy
      systemd:
        daemon_reload: yes
        service: proxyvm
        enabled: yes
        state: started
      when: copy_service.changed
