- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Install packages
      yum:
        name:
          - libvirt
          - libvirt-devel
          - ruby-devel
          - gcc
          - qemu-kvm
          - make
          - automake
          - gcc
          - gcc-c++
          - kernel-devel
          - python-devel
          - libvirt-devel

    - name: Start libvirtd
      systemd:
        service: libvirtd
        state: started

    - name: Install pip
      shell: |
        curl https://bootstrap.pypa.io/get-pip.py | python

    - name: Install virtualenv
      pip:
        name: virtualenv

    - name: Manually create the initial virtualenv
      command:
        cmd: virtualenv /root/venv
        creates: "/root/venv"

    - name: Install python library
      pip:
        name:
          - ansible
          - lxml
          - selinux
          - libvirt-python==5.0.0
          - virtualbmc==1.4.0
        virtualenv: /root/venv

    - name: Install vagrant
      yum:
        name: 'https://releases.hashicorp.com/vagrant/2.2.7/vagrant_2.2.7_x86_64.rpm'

    - name: Create ssh proxy service
      copy:
        src: files/proxy.service
        dest: /usr/lib/systemd/system/proxyvm.service
      register: copy_service

    - name: Start proxy
      systemd:
        daemon_reload: yes
        service: proxyvm
        enabled: yes
        state: started
      when: copy_service.changed

    - name: Create virsh net pxe
      virt_net:
        autostart: yes
        command: define
        name: "pxe"
        xml: '{{ lookup("template", "files/pxe.xml") }}'

    - name: Create virsh net internal
      virt_net:
        autostart: yes
        command: define
        name: "internal"
        xml: '{{ lookup("template", "files/internal.xml") }}'

    - name: Create virsh net nat
      virt_net:
        autostart: yes
        command: define
        name: "nat"
        xml: '{{ lookup("template", "files/nat.xml") }}'




